// remove this (?): CodeMirror, copyright (c) by Marijn Haverbeke and others
// remove this (?): Distributed under an MIT license: https://codemirror.net/LICENSE

// DO NOT EDIT - AUTOGENERATED
//
// This mode has been autogenerated from the Pygments lexer [1] by the script [2].
//
// [1]: ('...',)
// [2]: https://github.com/ComFreek/mmtpygments/blob/master/mmtpygments/pygments_to_codemirror.py

function loadGlifHighlighting(CodeMirror) {
    "use strict";

    ('',)

    CodeMirror.defineAdvancedMode("GLIF", {
		"start": [
				{regex: /--.*$/um, token: "comment"},
				{regex: /(abstract|resource|interface|concrete|instance)(\s+)(\w+)/um, token: ["keyword", "whitespace", "variable"]},
				{regex: /(case|in(?:(?:complete)?)|let|o(?:f|pen|verload)|table|with)\b/um, token: "keyword"},
				{regex: /(cat|d(?:ata|ef)|f(?:lags|un)|lin(?:(?:cat|(?:[dr])ef)?)|oper|param)\b/um, token: 'Generic.Heading'},
				{regex: /"([^"]|(\\"))*"/um, token: "string"},
				{regex: /\w+/um, token: 'Name'},
		],
	});
}
