// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TypingPred = 1,
  ModulePred = 2,
  ElpiKeyword = 3,
  other_token = 17,
  LineComment = 4,
  Program = 5,
  Rule = 6,
  HeadHead = 7,
  Variable = 8,
  Discard_variable = 9,
  String = 10,
  Int = 11,
  Operator = 12,
  Period = 13
