// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TypingPred = 1,
  ModulePred = 2,
  ElpiKeyword = 3,
  other_token = 18,
  LineComment = 4,
  BlockComment = 5,
  Program = 6,
  Rule = 7,
  HeadHead = 8,
  Variable = 9,
  Discard_variable = 10,
  String = 11,
  Int = 12,
  Operator = 13,
  Period = 14
