// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specialize_elpi_ident} from "./elpitokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#fQYQPOOOOQO'#Cc'#CcO`QPO'#CpO`QPO'#CrOeQPO'#CsOOQO'#Cb'#CbOOQO'#Cj'#CjQYQPOOOeQPO,59[O!PQPO,59^OOQO'#Ck'#CkO!UQPO'#CqO!pQPO,59_OOQO-E6h-E6hO!uQPO1G.vOOQO1G.x1G.xOOQO-E6i-E6iOOQO1G.y1G.yOOQO7+$b7+$b",
  stateData: "!z~OcOSSOS~OPQOQROaPO~ORYOWYOXYOYYOZYO[YOaYO]eP~O]_O~ORYOWYOXYOYYOZYO[YOaYO]eX~O]aO~O]bO~O",
  goto: "!`hPPPPPPimPPPPPPw}PPPP!U!Y!U!UTUOVSSOVQWQRXRQVOR]VSZSWR`ZTTOVQ[SR^W",
  nodeNames: "⚠ TypingPred ModulePred ElpiKeyword LineComment Program Rule HeadHead Variable Discard_variable String Int Operator Period",
  maxTerm: 24,
  skippedNodes: [0,4],
  repeatNodeCount: 2,
  tokenData: "&Y~R^XY}YZ}]^}pq}rs!`uv#|}!O$e!O!P$p!Q![$u!_!`$k!c!}$}#O#P$k#R#S%`#T#o%w~!SSc~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}OY~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RSS~OY#|Z;'S#|;'S;=`$_<%lO#|~$bP;=`<%l#|~$hP!`!a$k~$pO[~~$uO]~~$zPZ~!Q![$u~%SSW~!Q![$}!c!}$}#R#S$}#T#o$}~%cP!c!}%f~%kSX~!Q![%f!c!}%f#R#S%f#T#o%f~%|Sh~!Q![%w!c!}%w#R#S%w#T#o%w",
  tokenizers: [0],
  topRules: {"Program":[0,5]},
  specialized: [{term: 24, get: (value, stack) => (specialize_elpi_ident(value, stack) << 1), external: specialize_elpi_ident}],
  tokenPrec: 0
})
